language: python
python:
  - "3.5"
branches:
  only:
  - master
install:
- pip install -r requirements.txt

script:
#- make publish
- pelican content -s publishconf.py -D 
deploy:
  provider: pages
  local_dir: ../output
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  # only deploy on "main" branch
  on:
    branch: gh-pages