# ruby and sass for css generation in theme bootstrap4pelican
#language: ruby
#rvm:
#  - 2.3.1

language: sass
before_install:
- gem install sass

# pelican build process
language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
#- make publish
- pelican content -s publishconf.py -D
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: output
  target_branch: gh-pages
  on:
    branch: master