language: python
python:
  - "3.5"
branches:
  only:
  - master
install:
- pip install -r requirements.txt

script:
- make publish
deploy:
  provider: pages
  local_dir: ./output
  skip_cleanup: true
  github_token: $GIT_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
