jobs:
  - job: 'BuildPelicanSite'
    #continueOnError: True
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'
      #  - script: . setup.sh
    - script: pip install -r requirements.txt
      displayName: 'Install Requirements'
    - script: pelican content -o output
      displayName: 'Build Pelican Site To Output'




